# Form implementation generated from reading ui file './salemanagement/UI/MainProgram.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 651)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuManagement = QtWidgets.QMenu(parent=self.menubar)
        self.menuManagement.setObjectName("menuManagement")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTho_t_ph_n_m_m = QtGui.QAction(parent=MainWindow)
        self.actionTho_t_ph_n_m_m.setObjectName("actionTho_t_ph_n_m_m")
        self.actionChangePassword = QtGui.QAction(parent=MainWindow)
        self.actionChangePassword.setObjectName("actionChangePassword")
        self.actionSetting = QtGui.QAction(parent=MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./salemanagement/UI\\../Images/Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionAccountInfo = QtGui.QAction(parent=MainWindow)
        self.actionAccountInfo.setObjectName("actionAccountInfo")
        self.actionCategoryManagement = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./salemanagement/UI\\../Images/stock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCategoryManagement.setIcon(icon1)
        self.actionCategoryManagement.setObjectName("actionCategoryManagement")
        self.actionOrderManagement = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./salemanagement/UI\\../Images/Order.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOrderManagement.setIcon(icon2)
        self.actionOrderManagement.setObjectName("actionOrderManagement")
        self.actionEmployeeManagement = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./salemanagement/UI\\../Images/employee.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionEmployeeManagement.setIcon(icon3)
        self.actionEmployeeManagement.setObjectName("actionEmployeeManagement")
        self.menuSystem.addAction(self.actionAccountInfo)
        self.menuSystem.addAction(self.actionChangePassword)
        self.menuSystem.addAction(self.actionSetting)
        self.menuSystem.addAction(self.actionExit)
        self.menuManagement.addAction(self.actionCategoryManagement)
        self.menuManagement.addAction(self.actionOrderManagement)
        self.menuManagement.addAction(self.actionEmployeeManagement)
        self.menubar.addAction(self.menuSystem.menuAction())
        self.menubar.addAction(self.menuManagement.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuSystem.setTitle(_translate("MainWindow", "Hệ thống"))
        self.menuManagement.setTitle(_translate("MainWindow", "Quản lý"))
        self.actionTho_t_ph_n_m_m.setText(_translate("MainWindow", "Thoát phần mêm"))
        self.actionChangePassword.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.actionSetting.setText(_translate("MainWindow", "Cấu hình hệ thống"))
        self.actionExit.setText(_translate("MainWindow", "Thoát phần mềm"))
        self.actionAccountInfo.setText(_translate("MainWindow", "Thông tin tài khoản"))
        self.actionCategoryManagement.setText(_translate("MainWindow", "Quản lý sản phẩm - danh mục"))
        self.actionOrderManagement.setText(_translate("MainWindow", "Quản lý đơn hàng"))
        self.actionEmployeeManagement.setText(_translate("MainWindow", "Quản lý nhân viên"))
