# Form implementation generated from reading ui file './Class_Exercises/Buoi_4/salemanagement/UI/MainProgram.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 100, 451, 281))
        font = QtGui.QFont()
        font.setPointSize(39)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonReturnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonReturnLogin.setGeometry(QtCore.QRect(330, 430, 141, 28))
        self.pushButtonReturnLogin.setObjectName("pushButtonReturnLogin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionThongtintaikhoan = QtGui.QAction(parent=MainWindow)
        self.actionThongtintaikhoan.setObjectName("actionThongtintaikhoan")
        self.actionchangepassword = QtGui.QAction(parent=MainWindow)
        self.actionchangepassword.setObjectName("actionchangepassword")
        self.actionSetting = QtGui.QAction(parent=MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuSystem.addAction(self.actionThongtintaikhoan)
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionchangepassword)
        self.menuSystem.addAction(self.actionSetting)
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionExit)
        self.menubar.addAction(self.menuSystem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MAIN SCREEN"))
        self.pushButtonReturnLogin.setText(_translate("MainWindow", "Return to login"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.actionThongtintaikhoan.setText(_translate("MainWindow", "Thông tin người dùng"))
        self.actionchangepassword.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.actionSetting.setText(_translate("MainWindow", "Cấu hình hệ thống"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
